Fixes getViewContentManager error
ZupIT/beagle-web-angular pull request #199
Opened 2020-10-02 13:32 UTC by hectorcustodiozup

closes #197 

**- What I did**
Fixed error that caused the application to crash when using Ivy due to an undefined reference to the function getViewContentManager. I left documented on the issue(#197 ) some other approaches I have tried before finding this solution

**- How I did it**
Removed old reference to 'ng' which is an angular utils that should only be used in development mode
Added to the generate template an Input and an Id to reference itself, Those can then be accessed from the directive.

To test the solution I created an angular application and ran it with both Ivy enabled and disabled, I also tested with the project beagle forms for angular and finally  using a branch from the mfi project. All of them were built, executed and rendered without further problems 

**- How to verify it**
Use this branch in a project which has Ivy enabled

**- Description for the changelog**

2020-10-02 13:51 UTC, carolinegoncalveszup submitted a review, later dismissed

2020-10-02 18:07 UTC, Tiagoperes requested changes
Boa Hector! Sobre esses testes que vc falou, tem certeza que testou ambos Ivy e View Engine em ambos ambientes dev e produção?

Coloquei alguns comentários sobre a organização do código.

2020-10-02 18:07 UTC, Tiagoperes commented on src/runtime/view-content-manager/directive.ts
> +  @Input() selfReference: any
Aqui é um caso bem especial para a utilização do "_". Qualquer input colocado aqui passa a ser um atributo reservado do Beagle. Imagine que algum dev desenvolveu um custom component que tem a propriedade `selfReference`. Esse código vai quebrar tal aplicação e o dev não vai ter ideia do que aconteceu.

Para evitar esses conflitos de nomes, inputs que servem para controle interno do Beagle, são iniciados com "_". Veja o exemplo do _elementId e do _viewId.

2020-10-02 18:07 UTC, Tiagoperes commented on src/codegen/utils/template-builder.ts
> +      #self [selfReference]="self"
`#self [selfReference]="self"` é um atributo da diretiva, portanto, deveria ter sido declarado junto a variável `contextDirective`.

```typescript
const contextDirective = `${viewContentManagerSelector} [_elementId]="beagleId" [_viewId]="viewId" #self [selfReference]="self"`
// ...
<${selector} ${componentInputs} ${contextDirective} [attr.data-beagle-id]="beagleId" [ngClass]="styleId || ''" [ngStyle]="style">
```

2020-10-02 19:04 UTC, hectorcustodiozup commented
> Boa Hector! Sobre esses testes que vc falou, tem certeza que testou ambos Ivy e View Engine em ambos ambientes dev e produção?
> 

Eu testei das da seguinte maneira:
Alterei o enbableIvy no tsconfig das aplicações 
Buildei e rodei o projeto com o yarn serve
Buildei com yarn build e rodei com o lite-server

Fiz esses processos para o ivy com valores true e false

2020-10-06 16:37 UTC, carolinegoncalveszup approved these changes

2020-10-07 19:04 UTC, Tiagoperes approved these changes

2020-10-07 19:07 UTC, merged