Incrementing the ammount of unit tests
ZupIT/beagle-web-angular pull request #209
Opened 2020-10-25 22:25 UTC by osmarpetry

**- What I did**
Incremented more tests to the project

**- How I did it**
I started to create tests in the`--watch` mode, just increment some of then, not all tests I want

**- How to verify it**
Read the code and run all the unit tests 

**- Description for the changelog**

More unit tests to Angular

2020-10-26 20:23 UTC, Tiagoperes commented
Thank you for your contribution Osmar. I'll review it as soon as possible!

2020-10-27 16:20 UTC, osmarpetry commented
> Thank you for your contribution Osmar. I'll review it as soon as possible!

I did the same on inputs to check `readonly` and `disabled` from `beagle-web-react`. If don't want it, I can easily remove it here. Just did it on JS, because HTML can't prevent the value to change

2020-10-29 20:54 UTC, Tiagoperes commented
Hi Osmar, sorry for the long delays, we're quite busy here.

Since these tests are analogous to the ones you implemented for React, I'll wait for thos to be approved before checking these. Ok?

2020-11-09 14:24 UTC, Tiagoperes requested changes

2020-11-09 14:24 UTC, Tiagoperes commented on src/__tests__/components/beagle-button.spec.ts
> +  it('should trigger handleClick function when is disabled', () => {
should **not** trigger

2020-11-09 14:24 UTC, Tiagoperes commented on src/components/beagle-button/beagle-button.component.ts
> +    this.onPress && this.type === 'button' && !this.disabled && this.onPress()
For the same reason explained in the react PR, the logic here was correct. There's no need to add this verification for the attribute `disabled`.

We should not make a logic in the source code more complex just to suit a test.

As I said before, to test for a disabled button you should just check if the final button element in the HTML received the attribute "disabled". If it did, we know the browser works, so it won't call the handler once pressed. We must trust the browser is working, we should test only our application, never the browser.

2020-11-09 23:37 UTC, osmarpetry commented on src/components/beagle-button/beagle-button.component.ts
> +    this.onPress && this.type === 'button' && !this.disabled && this.onPress()
I thought I have removed this alteration from the PR. I will check it, in home on the computer

2020-11-21 21:43 UTC, osmarpetry commented
@Tiagoperes  I did the required changes

2020-11-30 12:24 UTC, Tiagoperes submitted a review, later dismissed

2020-11-30 13:03 UTC, Tiagoperes approved these changes

2020-11-30 13:10 UTC, carolinegoncalveszup approved these changes

2020-11-30 13:18 UTC, merged