Adds platform property
ZupIT/beagle-web-angular pull request #218
Opened 2020-11-10 16:44 UTC by hectorcustodiozup

**- What I did**
Added new default value for the new BeagleConfig property 'platform'. This value is used when the analytics is enabled
**- How I did it**

**- How to verify it**

**- Description for the changelog**

2020-11-17 21:03 UTC, carolinegoncalveszup commented on src/types.ts
> +export interface BeagleAngularConfig<Schema> extends Omit<BeagleConfig<Schema>, 'platform'> {
No beagle web core precisamos reimplementar o Omit por compatibilidade com versões mais antigas. Acho que faz sentido, para evitar problemas de incompatibilidade, importar o Omit do beagle web core.

2020-11-18 14:17 UTC, Tiagoperes requested changes

2020-11-18 14:17 UTC, Tiagoperes commented on src/types.ts
> +export interface BeagleAngularConfig<Schema> extends Omit<BeagleConfig<Schema>, 'platform'> {
A Carol tem razão. Se esse `Omit` é o `Omit` do typescript, não vai funcionar nas versões 7 e 8 do Angular. Precisa fazer `import { Omit } from '@zup-it/beagle-web'`

2020-11-26 12:34 UTC, Tiagoperes submitted a review, later dismissed

2020-11-26 13:35 UTC, Tiagoperes approved these changes

2020-11-26 14:13 UTC, carolinegoncalveszup approved these changes

2020-11-26 14:26 UTC, merged