Fix/questions
ZupIT/beagle-web-angular pull request #224
Opened 2021-01-05 20:57 UTC by jamessonpenhazup

**- What I did**

I removed unnecessary questions to make the script smaller and faster

**- How I did it**

Removed the configuration questions, leaving only the choice of the package manager, the other settings are set as default

**- How to verify it**

Create a new project and run yarn / npx add @ zup-it / beagle-angular

**- Description for the changelog**

Removed unnecessary questions to make the script smaller and faster

2021-01-06 12:28 UTC, Tiagoperes reviewed
James, quer aproveitar que vc está mexendo nessa parte do código e já corrigir uns outro problema simples? Tem alguns logs no cli falando sobre "ViewEngine" e "Ivy". Isso era uma ideia que tínhamos no começo e não virou nada. Precisamos tirar isso dos logs. Não deve-se mecionar nem "ViewEngine" nem "Ivy".

2021-01-06 12:28 UTC, Tiagoperes commented on src/cli/operations/init/questions.ts
> +async function setBeagleModule() {
o prefixo "set" da ideia de que a operação terá algum efeito colateral e que o valor de algo irá mudar. Isso não acontece aqui, portanto é uma escolha ruim de nome.

Na verdade vc está fazendo exatamente o contrário, vc não está "setando" um dado, vc está obtendo uma informação (get).

Sugestão: `getBeagleModuleInfo()`

2021-01-06 12:28 UTC, Tiagoperes commented on src/cli/operations/init/questions.ts
> +  const baseUrl = 'https://api.jsonbin.io/b'
use o json em: `https://usebeagle.io/start/home`

2021-02-05 16:57 UTC, Tiagoperes requested changes
There are non-resolved comments

2021-02-08 21:27 UTC, arthurbleilzup approved these changes

2021-02-12 18:55 UTC, Tiagoperes approved these changes

2021-02-12 18:56 UTC, merged