Fix/retry beagle error
ZupIT/beagle-web-angular pull request #225
Opened 2021-01-26 14:35 UTC by Bleil

**- What I did**
Following the pattern of the component on the Android environment, I created the same behavior on the component, allowing the user to retry the action that he was trying to do. Also, I added the errors list, that is provided by the core, showing to the user what could happened.

P.S.: The detailed messages are hidden and only will be displayed if the user clicks on "Show details".

**- How I did it**
Followed the pattern of components already developed on the project, keeping the behavior of Android environment and added useful information about what happened, giving details about the errors.

**- How to verify it**
1. After building the project, link it using yarn and create a new React project installing beagle. 
2. Then link your built project
3. On your test React project, create a JSON with this content:
`{
            "_beagleComponent_": "beagle:lazycomponent",
            "path": "/listview.json",
            "initialState": {
                "_beagleComponent_": "beagle:text",
                "text": "Loading the screen, please wait",
                "textColor": "grey",
                "alignment": "CENTER"
            }
        }`
4.  Then start your application, it should display the error message, because we do not have created the "listview.json" that _beagle:lazycomponent_ requires, showing you the error component.

**- Description for the changelog**

2021-02-05 16:54 UTC, Tiagoperes requested changes

2021-02-05 16:54 UTC, Tiagoperes commented on angular.json
> +    "analytics": "3d430695-a623-4d28-a099-8e0346b09ec8"
What is this? Should it have been committed?

2021-02-05 16:54 UTC, Tiagoperes commented on src/components/beagle-error/beagle-error.component.html
> +<button type="button" (click)="retry()" class="retry-button">Retry</button>
Instead of altering the styles in the previous files, could you have instead just used the component with the selector`<beagle-button>`?

2021-02-05 16:54 UTC, Tiagoperes commented on src/components/beagle-error/beagle-error.component.ts
> +export class BeagleErrorComponent extends BeagleComponent implements ErrorComponentParams {
Como seu componente não usa nada específico do Beagle, não precisa extender BeagleComponent.

2021-02-06 18:51 UTC, arthurbleilzup commented on angular.json
> +    "analytics": "3d430695-a623-4d28-a099-8e0346b09ec8"
No, when I used CLI it automatically created, it is fixed now

2021-02-06 18:52 UTC, arthurbleilzup commented on src/components/beagle-error/beagle-error.component.html
> +<button type="button" (click)="retry()" class="retry-button">Retry</button>
It was having a problem related to Analytics, so it is solved now and is using `<beagle-button>` right now

2021-02-06 18:53 UTC, arthurbleilzup commented on src/components/beagle-error/beagle-error.component.ts
> +export class BeagleErrorComponent extends BeagleComponent implements ErrorComponentParams {
Got it, it is fixed now

2021-02-08 18:32 UTC, hectorcustodiozup approved these changes

2021-02-12 19:04 UTC, Tiagoperes approved these changes

2021-02-12 19:04 UTC, merged