Adds input form validation
ZupIT/beagle-web-angular pull request #226
Opened 2021-01-31 20:27 UTC by hectorcustodiozup

**- What I did**
Following the EPIC (https://github.com/ZupIT/beagle/issues/883) added form error validation

**- How I did it**
Altered the components Input and SimpleForm to accept two new properties 'error' and showError'

**- How to verify it**
Run this branch and pass the two new properties to the component

**- Description for the changelog**
Adds form validation

2021-02-05 17:27 UTC, Tiagoperes requested changes

2021-02-05 17:27 UTC, Tiagoperes commented on src/components/beagle-input/beagle-input.component.ts
> +    this.showError = true
No, you should not be controlling this. This behavior is controlled by Beagle.

2021-02-05 17:27 UTC, Tiagoperes commented on src/components/beagle-input/beagle-input.component.html
> +    id="{{error ? '_beagleFormError' : ''}}"
An element id must be unique. You can't assign the same id for every beagle-input with error. Furthermore, ids should be static, an element id should not change according to a state.

It would be ok if instead of an id it was a class.

2021-02-05 17:27 UTC, Tiagoperes commented on src/components/beagle-simple-form/beagle-simple-form.component.ts
> +    if (document && document.getElementById('_beagleFormError'))
This is not ok for two reasons:

1. Id's must be unique and static, you can't verify a state trough an id.
2. There could be many forms in the current page, you can't prevent a form from being submitted because another form has an error.

The correct way to verify if there are errors is to check for the class `hasError`. Moreover, you can't check it considering the entire page, you must look only inside the current form.

2021-02-05 21:09 UTC, hectorcustodiozup commented on src/components/beagle-simple-form/beagle-simple-form.component.ts
> +    if (document && document.getElementById('_beagleFormError'))
Fixed it using a class instead of id. I could not however use the `hasError` class because its condition is `error && showError` but the `onValidationError` method should be called if at least error is true and not both.

2021-02-08 21:26 UTC, arthurbleilzup requested changes

2021-02-08 21:26 UTC, arthurbleilzup commented on src/components/beagle-simple-form/beagle-simple-form.component.ts
> +import { Console } from 'console'
is this Console necessary?

2021-02-08 21:36 UTC, hectorcustodiozup commented on src/components/beagle-simple-form/beagle-simple-form.component.ts
> +import { Console } from 'console'
Fixed

2021-02-08 21:36 UTC, arthurbleilzup submitted a review, later dismissed

2021-02-12 19:16 UTC, Tiagoperes requested changes

2021-02-12 19:16 UTC, Tiagoperes commented on src/components/beagle-simple-form/beagle-simple-form.component.ts
> +        {if (this.lookUpInputErrors(item)) return true}
This construction can be hard to read. Prefer logic operators instead of nested ifs.

```typescript
if (item.children && this.lookUpInputErrors(item)) return true
```

2021-02-12 19:18 UTC, Tiagoperes submitted a review, later dismissed

2021-02-12 19:36 UTC, arthurbleilzup approved these changes

2021-02-12 19:45 UTC, Tiagoperes approved these changes

2021-02-12 20:11 UTC, merged