Fix/changes button input name
ZupIT/beagle-web-angular pull request #227
Opened 2021-02-09 16:45 UTC by hectorcustodiozup

**- What I did**
Changed Input name
**- How I did it**
Changed from disabled to enabled
**- How to verify it**
Using the button component
**- Description for the changelog**

2021-02-10 17:15 UTC, tayronemachadozup submitted a review, later dismissed

2021-02-12 19:35 UTC, Tiagoperes requested changes

2021-02-12 19:35 UTC, Tiagoperes commented on src/components/beagle-button/beagle-button.component.html
> +  [disabled]="enabled"
Be careful with names. To say that disabled equals to enabled is like saying true equals to false. I'd expect to see here `[disabled]="disabled"` or `[disabled]="!enabled"`

2021-02-12 19:35 UTC, Tiagoperes commented on src/components/beagle-button/beagle-button.component.ts
> +    this.enabled = this.enabled === undefined ? false : !this.enabled
This line is confusing. All because you're trying to name `disabled` and `enabled` the same. This is not a good idea.

My suggestion here is that you keep a variable called `disabled` and its value is going to be:
```typescript
this.disabled = this.enabled === undefined ? false : !this.enabled
```

Then, in the html, you use `[disabled]="disabled"`

2021-02-12 20:10 UTC, Tiagoperes approved these changes

2021-02-12 20:10 UTC, Tiagoperes commented
A test snapshot is failing

2021-02-17 19:00 UTC, Tiagoperes submitted a review, later dismissed

2021-02-19 14:47 UTC, tayronemachadozup submitted a review, later dismissed

2021-02-19 20:30 UTC, tayronemachadozup approved these changes

2021-02-23 13:54 UTC, Tiagoperes approved these changes

2021-02-23 13:54 UTC, merged