Allow text component to render not only strings
ZupIT/beagle-web-angular pull request #232
Opened 2021-02-24 20:48 UTC by arthurbleilzup

**- What I did**
As context will be able to change it's type on the web core project, I identified that the text component was not able to render the object values, crashing the application, so I changed the render method to be able to parse the data to a readable string

**- How I did it**
When the text attribute is changed, runs a validation of data type, then try to parse it as a string, rendering the text of the component as a readable string.  

**- How to verify it**
You can start a context with a string then set the context with a `path` and see the value change, you can use the following json to test:

https://run.mocky.io/v3/3797bd95-5837-4225-8b7a-edefbbed0f5f

2021-02-25 14:19 UTC, hectorcustodiozup approved these changes

2021-02-25 17:39 UTC, tayronemachadozup approved these changes

2021-03-02 12:39 UTC, igorgiumellizup requested changes

2021-03-02 12:39 UTC, igorgiumellizup commented on src/__tests__/components/beagle-text.spec.ts
> +  it('should render not render any text when text is null', () => {
```suggestion
  it('should not render any text when text is null', () => {
```

2021-03-02 12:39 UTC, igorgiumellizup commented on src/__tests__/components/beagle-text.spec.ts
> +  it('should render not render any text when text is undefined', () => {
```suggestion
  it('should not render any text when text is undefined', () => {
```

2021-03-02 12:39 UTC, igorgiumellizup commented on src/__tests__/components/beagle-text.spec.ts
> +  it('should render an function as empty string', () => {
```suggestion
  it('should render a function as empty string', () => {
```

2021-03-02 14:50 UTC, hectorcustodiozup approved these changes

2021-03-03 18:33 UTC, jamessonpenhazup approved these changes

2021-03-04 12:53 UTC, igorgiumellizup approved these changes

2021-03-04 12:54 UTC, merged