Fix/deprecated field disabled
ZupIT/beagle-web-angular pull request #241
Opened 2021-03-24 18:16 UTC by tayronemachadozup

Issue https://github.com/ZupIT/beagle/issues/1401

**- What I did**
Create field enabled in text input and deprecated field disabled

**- How to verify it**
Was tested through a angular poc

2021-03-24 18:25 UTC, arthurbleilzup submitted a review, later dismissed

2021-04-06 12:57 UTC, Tiagoperes requested changes

2021-04-06 12:57 UTC, Tiagoperes commented on src/components/beagle-input/beagle-input.component.html
> +    [disabled]="!inputEnabled"
Have you tested this? Maybe Angular does something about it, but, in HTML, `disabled="false"` is the same as `disabled="true"`. This is because `disabled` doesn't actually accepts a value, it exists or it doesn't. I totally disagree with this unintuitive approach, but it is what it is.

2021-04-06 12:57 UTC, Tiagoperes commented on src/components/beagle-input/beagle-input.component.ts
> +  *  Use field enabled to control is enabled or not in this layout.
`Use field enabled to control is enabled or not in this layout.`

Since this is part of the documentation, I must correct the english here =(. The correct way to say this would be: ``Use field `enabled` to control whether the button is enabled or not in the layout``.

In any case, I'd suggest something simpler: ``@deprecated since version 1.7.0. Use `enabled` instead.``

2021-04-06 12:57 UTC, Tiagoperes commented on src/components/beagle-input/beagle-input.component.ts
> +  * @Deprecated It was deprecated in version 1.7.0 and will be removed in a future version.
should be `@deprecated`, with a lowercase "d".

2021-04-06 12:57 UTC, Tiagoperes commented on src/components/beagle-input/beagle-input.component.ts
> +  }
**suggestion**

this could be simpler:

```typescript
public get inputEnabled(): boolean {
  return enabled !== false && disabled !== true
}
```

2021-04-06 12:57 UTC, Tiagoperes commented on src/components/beagle-input/beagle-input.component.html
> +    [attr.aria-disabled]="!inputEnabled"
Here it is correct, `aria-disabled`, differently than `disabled`, accepts a boolean.

2021-04-06 13:06 UTC, arthurbleilzup commented on src/components/beagle-input/beagle-input.component.html
> +    [disabled]="!inputEnabled"
Here was used the directive `[disabled]`, that is built-in Angular, which expect a `boolean` value, differently than `[attr.disabled]` which has the behavior that you mentioned, where if there is any kind on defined value the input would be disabled. So this `[disabled]` is a good approach, also considering that we make sure that is always a `boolean`.

2021-04-06 20:10 UTC, Tiagoperes approved these changes

2021-04-12 19:12 UTC, arthurbleilzup approved these changes

2021-04-12 19:12 UTC, merged