fix modal
ZupIT/beagle-web-angular pull request #243
Opened 2021-04-19 13:03 UTC by gabrielpenhazup

What did I do
I made the necessary corrections so that no component overlaps the modal. Closes #242

2021-04-19 14:35 UTC, tayronemachadozup commented
Gabriel follows the description patterns of a pr

2021-04-19 15:17 UTC, arthurbleilzup requested changes
Please follow the PR guidelines as @tayronearaujo mentioned

2021-04-19 15:17 UTC, arthurbleilzup commented on src/components/beagle-modal/beagle-modal.component.less
> +  z-index: 1;
I was wondering about this change and trying to think if there was a scenario where `z-index: 1` wouldn't be effective... well, beyond the Beagle elements it will not impact, only `BeagleModal` uses that behavior. 

On other hand, the developers that use Beagle can develop components that overlap this change, but there are more than one solution for that, that are the users implementing their features differently or overriding the style of `BeagleModal`, so I believe this is a good solution.

Ps. Sorry for the long text, just leaving my thoughts here, as reflection for next features...

2021-04-20 14:57 UTC, Tiagoperes approved these changes

2021-04-20 15:11 UTC, arthurbleilzup approved these changes

2021-04-20 15:11 UTC, merged