Feature/gridview
ZupIT/beagle-web-angular pull request #245
Opened 2021-04-27 18:28 UTC by hectorcustodiozup

**- What I did**
Added new component beagle:gridview

**- How I did it**
It was created a new component with its own interface and HTML, reused some parts of the Listview component that were common between the two of them

**- How to verify it**
Use the new component beagle:gridview and pass its new property numColumns

Result with 6 columns:

![image](https://user-images.githubusercontent.com/50678762/116293362-2e993b00-a76d-11eb-9ad3-d32873e88754.png)

**- Description for the changelog**
New component added: GridView

2021-04-29 13:18 UTC, Tiagoperes requested changes
### Problem

You repeated too much of the original list view. We should avoid at all costs this much code repetition. It makes maintenance very hard. I’m talking about the file `beagle-grid-view.component.ts `, this is basically a copy and paste from the the list view, and there’s way too much logic in this file for us to repeat it.

### Suggestion

`GridView` **IS** a `Dynamic List` and `ListView` is a `DyanamicList`. This relationship is simply expressed as an extension in Object Oriented Programming (OOC). Our UI tree is not OOC, we can’t extend a component. Normally, when dealing with UI we’d say `GridView` **USES** a `DynamicList` and `ListView` uses a `DynamicList`.

Normally, when we need to extend a UI component, we just use it inside the new component’s template:

Template for a button with animation:

```html
<my-button class=“animated”></my-button>
<div class=“animated-stuff>…</div>

```

In our case, the first thing we need to do is to create a component that can serve both the ListView and the GridView, i.e., we need to create the DynamicList. To do this:

1. Rename the ListView to DynamicList
2. Add the property “type: ‘list’ | ‘grid’” to the component
3. Add the property “”numColumns?: number” to the component

This component (DynamicList) must check the parameter “type” and render a list in the given `direction` if it’s a list or a grid with the given `numColumns` if it’s a grid.

Now you must create the ListView and the GridView. This is super-simple, you just need to use the component DynamicList:

ListView template:
```html
<DynamicList type=“list” …>
```

GridView template:
```html
<DynamicList type=“grid” …>
```

Where `…` means copy every property passed to the component.

2021-05-04 12:26 UTC, Tiagoperes requested changes

2021-05-04 12:26 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.component.html
> +  [attr.aria-rowcount]="type === 'LIST' && (direction === 'VERTICAL' ? this.dataSource.length : 1)"
These aria attributes should also work for GridView. My suggestion would be to create a function in the controller.

2021-05-04 12:26 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.component.ts
> +  }
sugestão: reduzir.

```typescript
return this.type === 'GRID' ? 'beagle-grid-view' : `beagle-list-view ${this.direction}`
```

2021-05-04 12:26 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.scroll.ts
> +    console.log('ScrollENd', this.direction)
remove logs

2021-05-04 12:27 UTC, Tiagoperes commented
We need snapshot test for the GridView. Replicate what we have today for the ListView.

2021-05-04 14:01 UTC, Tiagoperes commented
## Manual tests

#### I ran every ListView example of the playground to see if they still work as expected. I found the following bug:

The example ["5.nested.json"](https://playground.usebeagle.io/#/demo/listview/5.nested.json?platform=angular) has stopped working. It now runs every "onScrollEnd" event without ever scrolling.

#### I also ran every example switching ListView for GridView. Every example worked.

#### Tests with nested GridViews:

1. I placed a GridView inside another GridView. 1 element of the first grid view had a fixed id, 1 element of the second grid view also had a fixed id. As I expected, everything worked.
2. I placed a GridView inside a ListView. 1 element of the list view had a fixed id, 1 element of the grid view also had a fixed id. As I expected, this scenario HAS NOT WORKED. Many elements were generated with the same id, which can cause a lot of problems. This must be fixed.

Here's an [example](http://localhost:8080/#/cloud/S3-1dd573a4-9e95-41a2-b52b-3f4f4d8b5c95?platform=angular) for both of the scenarios above. The example "grid-grid.json" works, if you check the HTML tree, you'll see that each "touchable" will have a different data-beagle-id with the prefix "poster", starting at "poster:0:0". The example "list-grid.json", on the other hand, does not work, you'll see that every touchable has the prefix "poster", but has only one iteration level, starting at "poster:0". Because of this, there will be 3 elements in the tree where `data-beagle-id` is `"poster:0"`, you can check this by executing the following line in the playground:

```typescript
Array.from(document.querySelectorAll('[data-beagle-id]')).filter(e => e.getAttribute('data-beagle-id') === 'poster:0')
```

This error happens because of [this line of code](https://github.com/ZupIT/beagle-web-angular/blob/feature/gridview/src/components/dynamic-lists/dynamic-list.component.ts#L87). You'll probably have to drop the current strategy use a constant value.

2021-05-05 17:23 UTC, arthurbleilzup requested changes

2021-05-05 17:23 UTC, arthurbleilzup commented on src/components/dynamic-lists/dynamic-list.component.html
> +  [beagleAccessibility]= "accessibility">
Please follow the HTML patterns, even if it is Angular.

```suggestion
  [ngClass]="getClassForType()"
  [ngStyle]="{'grid-template-columns': type === 'GRID' && getColumnsQuantityStyle()}" 
  [attr.aria-colcount]="getColCount()"
  [attr.aria-rowcount]="getRowCount()" 
  [beagleAccessibility]="accessibility">
```

2021-05-05 17:23 UTC, arthurbleilzup commented on src/components/dynamic-lists/beagle-grid-view/beagle-grid-view.component.html
> +  [parentReference] = this>
Please follow the HTML patterns, even if it is Angular.

```suggestion
<beagle-dynamic-list 
  type="listType.Grid"
  [numColumns]="numColumns"
  [dataSource]="dataSource"
  [iteratorName]="iteratorName"
  [template]="template"
  [onInit]="onInit"
  [onScrollEnd] = onScrollEnd
  [scrollEndThreshold] = scrollEndThreshold
  [useParentScroll] = useParentScroll
  [key] = key
  [__suffix__]= __suffix__
  [isScrollIndicatorVisible] = isScrollIndicatorVisible
  [parentReference] = this>
```

2021-05-05 17:23 UTC, arthurbleilzup commented on src/components/dynamic-lists/beagle-list-view/beagle-list-view.component.html
> +  [parentReference] = this>
Please follow the HTML patterns, even if it is Angular.

```suggestion
<beagle-dynamic-list 
  type="listType.List"
  [direction]="direction"
  [dataSource]="dataSource"
  [iteratorName]="iteratorName"
  [template]="template" 
  [onInit]="onInit"
  [onScrollEnd]="onScrollEnd"
  [scrollEndThreshold]="scrollEndThreshold"
  [useParentScroll]="useParentScroll"
  [key]="key"
  [__suffix__]="__suffix__"
  [isScrollIndicatorVisible]"="isScrollIndicatorVisible"
  [parentReference]="this">
```

2021-05-05 17:23 UTC, arthurbleilzup commented on src/components/dynamic-lists/dynamic-list.component.ts
> +    return this.type === 'GRID' ? 'beagle-grid-view' :
Use the suggestion of creating a String Enum for Type and Direction.

```suggestion
    return this.type === ListType.Grid ? 'beagle-grid-view' :
```

2021-05-05 17:23 UTC, arthurbleilzup commented on src/components/dynamic-lists/dynamic-list.component.ts
> +    if (this.type === 'LIST')
Use the suggestion of creating a String Enum for Type and Direction.

```suggestion
    if (this.type === ListType.List) 
```

2021-05-05 17:23 UTC, arthurbleilzup commented on src/components/dynamic-lists/dynamic-list.component.ts
> +      {return this.direction === 'VERTICAL' ? this.dataSource.length : 1}
Use the suggestion of creating a String Enum for Type and Direction.

```suggestion
      {return this.direction === ListDirection.Vertical ? this.dataSource.length : 1}
```

2021-05-05 17:23 UTC, arthurbleilzup commented on src/components/dynamic-lists/dynamic-list.component.ts
> +      {return this.direction === 'VERTICAL' ? 1 : this.dataSource.length}
Use the suggestion of creating a String Enum for Type and Direction.

```suggestion
    if (this.type === ListType.List)  {
      return this.direction === ListDirection.Vertical ? 1 : this.dataSource.length
    }
```

2021-05-05 17:23 UTC, arthurbleilzup commented on src/components/schemas/dynamic-list.ts
> +}
On TypeScript, we are able to create [String Enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums), so would be a cleaner approach to use on the application, avoiding some casts using `as` and is easier to do maintenance and for new types of dynamic list. Other benefits are the ability to quickly find all references to the list type on the whole project structure and it is also really quicker to write, because using the auto-complete of your editor you do not have to worry about misspelling the string or validating it.

I suggest implement this (also valid for Direction) like this:

```suggestion
export enum ListType {
  Grid='GRID',
  List='LIST'
}

export enum ListDirection {
  Horizontal='HORIZONTAL',
  Vertical='VERTICAL'
}

export interface BeagleGridViewInterface extends DynamicListBaseInterface {  
  numColumns?: number,
}

export interface BeagleListViewInterface extends DynamicListBaseInterface{
  direction: ListDirection,
}

export interface DynamicListInterface extends BeagleGridViewInterface, BeagleGridViewInterface{
  type: ListType,
}
```

2021-05-06 13:33 UTC, Tiagoperes requested changes

2021-05-06 13:33 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.component.ts
> +  private idIncrement = 0
You're creating a new rule for assigning ids. Ids are very important and they must follow the same rule in every platform so they can be predicted when building the backend.

If you need to create a new rule for id assignment, you MUST discuss it with the team (all platforms) before doing so.

The current rule for id assignment works just fine. The problem is not the rule itself, it's a single scenario where the rule is not correctly applied. To fix this, you need to make sure that the rule is applied in every scenario, even when you have a GridView inside a ListView.

As I said before, the problem is the line 

```typescript
if (component._beagleComponent_.toLowerCase() === listViewTag)
```

According to this line, to apply the suffix rule, the component must be the of the same type of the List. For instance, if we're inside a ListView, it will apply the rule for every ListView in the template. If we're in a GridView, it will apply the rule for every GridView in the template. There's our problem. We must apply the suffix rule to every GridView and ListView, despite the parent.

Changing the condition to the following, would fix this without altering the rule itself:

```typescript
const LIST_COMPONENTS = ['beagle:listview', 'beagle:gridview']

// ...

if (LIST_COMPONENTS.includes(component._beagleComponent_.toLowerCase()))
```

2021-05-06 13:33 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.component.ts
> +    return this.numColumns && Math.round(this.dataSource.length / this.numColumns)
Imagine you have 4 items and 3 columns. The total number of rows will be 2: 3 items in the first row and 1 item in the second. Your calculus would give us 1 instead of 2.

Instead of `Math.random`, you can use `Math.ceil`

2021-05-06 13:33 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.component.ts
> +      this.getViewContentManager = this.parentReference.getViewContentManager
why, instead of passing the entire `this` you don't pass only the `viewContentManager`?

2021-05-06 13:33 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.component.ts
> +    if (changedElement != 'BEAGLE-DYNAMIC-LIST') return
use `!==` instead of `!=`

2021-05-06 13:33 UTC, Tiagoperes commented on src/components/schemas/dynamic-list.ts
> +export enum ListDirection {
We never use typescript enums in our projects. We should have a lint rule for this, so nobody attempts to do so.

enums are not valid javascript datatypes. Typescript makes a mess when generating javascript code for this. Besides, we have a perfectly fine way of expressing enums with less code and no drawbacks:

```typescript
  export type ListDirection = 'VERTICAL' | 'HORIZONTAL'
```

less code, same effect, no weird side-effects in javascript.

[Enums can also very easily be used in unsafe ways](https://blog.logrocket.com/why-typescript-enums-suck/), so since we have another better way of expressing them, we chose not to use the feature.

Please, undo the changes you've done to these types.

2021-05-06 13:42 UTC, hectorcustodiozup commented on src/components/dynamic-lists/dynamic-list.component.ts
> +      this.getViewContentManager = this.parentReference.getViewContentManager
I tried it so, but the build breaks and says that the viewContentManager property does not exist. I believe it has to do something with the rendering order

2021-05-06 14:24 UTC, arthurbleilzup commented on src/components/schemas/dynamic-list.ts
> +export enum ListDirection {
I see... I proposed the use of enum to be easier to code and to refer to those types, providing a better lint as well, but I did not knew about those side effects on thee production side, so please undo the changes about enums and I will approve the PR.

2021-05-06 15:17 UTC, Tiagoperes approved these changes

2021-05-06 15:18 UTC, arthurbleilzup approved these changes

2021-05-07 02:14 UTC, merged