Fix/merge fixes
ZupIT/beagle-web-angular pull request #269
Opened 2021-07-02 22:42 UTC by arthurbleilzup

Merge Fixes
pull request for inclusion in the changelog:
-->

2021-07-02 23:58 UTC, Tiagoperes requested changes

2021-07-02 23:58 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.component.ts
> +    return this.iteratorName || 'item'
There's still some code using this.iteratorName instead of this function. Please check.

2021-07-02 23:58 UTC, Tiagoperes commented on src/components/dynamic-lists/dynamic-list.component.ts
> +    s = [
Ahnnn. What? 😆

2021-07-05 17:41 UTC, arthurbleilzup commented on src/components/dynamic-lists/dynamic-list.component.ts
> +    return this.iteratorName || 'item'
Used a easier way to get the iterator name...

2021-07-05 18:00 UTC, arthurbleilzup commented on src/components/dynamic-lists/dynamic-list.component.ts
> +    s = [
I really do not know how it happened

2021-07-05 18:06 UTC, jamessonpenhazup submitted a review, later dismissed

2021-07-05 18:39 UTC, tayronemachadozup submitted a review, later dismissed

2021-07-05 18:41 UTC, jamessonpenhazup submitted a review, later dismissed

2021-07-05 18:51 UTC, jamessonpenhazup approved these changes

2021-07-05 18:51 UTC, tayronemachadozup approved these changes

2021-07-05 18:53 UTC, merged