Remove deprecate code
ZupIT/beagle-web-angular pull request #287
Opened 2021-09-03 17:35 UTC by tayronemachadozup

**- What I did**

Removed deprecated code of all beagle angular

**- How I did it**

Removing all @deprecated code and checking for possible impacts 

**- How to verify it**

Was verified through unit tests, pocs with angular and E2E test

**- Description for the changelog**

2021-09-09 13:23 UTC, Tiagoperes requested changes

2021-09-09 13:23 UTC, Tiagoperes commented on src/components/beagle-screen/beagle-screen.component.ts
> +  hasInitialized = false;
This variable doesn't need to exist anymore

2021-09-09 13:23 UTC, Tiagoperes commented on src/components/beagle-touchable/beagle-touchable.component.ts
>        const beagleService = beagleProvider.getBeagleUIService()
Be careful. Removing deprecated code means to also remove dependencies that are no longer used.

Why would you still need the two variables above? Why would you still need the injector?

2021-09-09 17:31 UTC, tayronemachadozup commented on src/components/beagle-touchable/beagle-touchable.component.ts
>        const beagleService = beagleProvider.getBeagleUIService()
The variables and the injector are unnecessary and must be removed

2021-09-09 20:42 UTC, arthurbleilzup approved these changes

2021-09-10 11:48 UTC, Tiagoperes approved these changes

2021-09-10 11:48 UTC, merged